{:user {:dependencies  [[hashp "0.2.0"]
                        [io.aviso/pretty "0.1.37"]
                        ;; [com.cognitect/REBL "0.9.240"]
                        ;; [djblue/portal  "0.8.0"]
                        ]
        :plugins [[io.aviso/pretty "0.1.37"]]
        ;:plugins [[cider/cider-nrepl  "0.21.1"]]
        :injections  [(require 'hashp.core)]
        :middleware [io.aviso.lein-pretty/inject]
        }}
